[package]
name = "tinc-pb-prost"
version = "0.1.6"
edition = "2024"
description = "Protobuf generated schama for tinc"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/tinc-pb"
license = "MIT OR Apache-2.0"
keywords = ["grpc", "protobuf", "prost", "codegen"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[features]
## Enables documentation of feature flags
docs = ["dep:document-features"]

[dependencies]
document-features = { optional = true, version = "0.2" }
prost = "0.13.5"
prost-types = "0.13.5"
scuffle-workspace-hack.workspace = true

[build-dependencies]
prost-build = "0.13.5"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "docsrs",
  "--sort-modules-by-appearance",
  "--generate-link-to-definition",
]

[package.metadata.xtask.powerset]
additive-features = ["docs"]

[package.metadata.cargo-sync-rdme.badge]
style = "flat-square"

[package.metadata.cargo-sync-rdme.badge.badges]
license = true
docs-rs = true
crates-io = true
github-actions = { workflows = "ci.yaml" }
codecov = true

[package.metadata.xtask.release]
group = "tinc"
