[package]
name = "scuffle-metrics-derive"
version = "0.1.2"
edition = "2024"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/scuffle-metrics-derive"
license = "MIT OR Apache-2.0"
description = "Derive macros for scuffle-metrics."
keywords = ["metrics", "derive", "macros"]

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
proc-macro2 = "1"
quote = "1"
scuffle-workspace-hack.workspace = true
syn = { features = ["full"], version = "2" }

[dev-dependencies]
scuffle-metrics = { path = "..", version = "0.2.0" }

[package.metadata.cargo-sync-rdme.badge]
style = "flat-square"

[package.metadata.cargo-sync-rdme.badge.badges]
license = true
docs-rs = true
crates-io = true
github-actions = { workflows = "ci.yaml" }
codecov = true
